#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import Joy

class PublisherJoy():

  def __init__(self):
    topic = 'topic_joy' # Cambiar el nombre del topico
    # Declarar del publicador
    self.pub = rospy.Publisher(topic, Joy, queue_size=1)

if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_publicador_joy')
    
    # Crear el objeto del publicador
    pub_joy = PublisherJoy()
    
    # Creación de una instancia (vacía) del mensaje
    joy_msg = Joy()

    # Tiempo de ejecución del bucle (en Hz)
    rate = rospy.Rate(10)    # 10hz
    while not rospy.is_shutdown():
        # Asignar los valores al mensaje
        joy_msg.header.stamp = rospy.Time.now()
        joy_msg.header.frame_id = 'frame_joy'
        joy_msg.axes = [1.1, 2.2, 3.3]
        joy_msg.buttons = [1, 0, 1]
        # Publicar el mensaje
        pub_joy.pub.publish(joy_msg)
        # Esperar
        rate.sleep()