#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Quaternion

# Función de callback
def callback_func(msg):
    print("Cuaternion leido: w={}, x={}, y={}, z={}".format(msg.w, msg.x, msg.y, msg.z))

if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_suscriptor_quat')

    # Declaración del suscriptor
    topic = 'topic_quat'
    pub = rospy.Subscriber(topic, Quaternion, callback_func)

    # Mantener el nodo activo (hasta que se detenga
    rospy.spin()

