#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import Joy

# Función de callback
def callback_func(msg):
    print("\nTiempo: " + str(msg.header.stamp))
    print("Frame leido: " + msg.header.frame_id)
    print("Ejes leidos: ")
    axes = msg.axes
    for i in range(len(axes)):
        print(str(axes[i]))

if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_suscriptor_joy')

    # Declaración del suscriptor
    topic = 'topic_joy'
    pub = rospy.Subscriber(topic, Joy, callback_func)

    # Mantener el nodo activo (hasta que se detenga
    rospy.spin()

