#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Pose

# Función de callback
def callback_func(msg):
    p = msg.position
    q = msg.orientation
    print("\nPosicion leida: x={}, y={}, z={}".format(p.x, p.y, p.z))
    print("Orientacion leida: w={}, x={}, y={}, z={}".format(q.w, q.x, q.y, q.z))

if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_suscriptor_pose')

    # Declaración del suscriptor
    topic = 'topic_pose'
    pub = rospy.Subscriber(topic, Pose, callback_func)

    # Mantener el nodo activo (hasta que se detenga
    rospy.spin()

