#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Point

# Función de callback
def callback_func(msg):
    print("Punto leido: x={}, y={}, z={}".format(msg.x, msg.y, msg.z))

if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_suscriptor_point')

    # Declaración del suscriptor
    topic = 'topic_point'
    pub = rospy.Subscriber(topic, Point, callback_func)

    # Mantener el nodo activo (hasta que se detenga
    rospy.spin()

